import { Metadata } from 'next';
import { COMPANY_NAME, ADDRESS, PHONE_NUMBER, EMAIL, WEBSITE, SOCIAL_LINKS, PO_BOX, ABOUT_US } from './constants';

export const siteConfig = {
  name: COMPANY_NAME,
  description: ABOUT_US.description,
  url: `https://${WEBSITE}`,
  ogImage: '/og-image.jpg',
  links: {
    instagram: SOCIAL_LINKS.instagram,
    facebook: SOCIAL_LINKS.facebook,
  },
};

export const defaultMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: `${COMPANY_NAME} | Building Materials, Electrical & Plumbing Supplies in Doha, Qatar`,
    template: `%s | ${COMPANY_NAME}`,
  },
  description: siteConfig.description,
  keywords: [
    'building materials Qatar',
    'electrical supplies Qatar',
    'construction materials Doha',
    'electrical cables Qatar',
    'plumbing supplies Qatar',
    'hardware store Qatar',
    'Al Alis building materials',
    'construction supplier Qatar',
    'electrical distributor Qatar',
    'building materials supplier Doha',
    'sanitary ware Qatar',
    'power tools Qatar',
    'PPE equipment Qatar',
    'fire safety equipment Qatar',
    'ladders scaffolding Qatar',
    'hardware Doha',
    'plumbing Doha',
    'electrical materials Qatar',
    'building hardware Qatar',
    'construction supplies Qatar',
    'electrical wholesalers Qatar',
    'plumbing wholesalers Doha',
    'Al Alis Qatar',
    'Al Alis Doha',
    'electrical cables Doha',
    'power tools Doha',
    'PPE Qatar',
    'fire safety Doha',
    'ladders Qatar',
    'scaffolding Doha',
    'sanitary ware Doha',
    'retail chain Qatar',
    'building materials retail Doha',
    'electrical retail Qatar',
    'plumbing retail Doha',
    'construction hardware Doha',
    'electrical supplies Doha',
    'plumbing materials Qatar',
    'building supplies Qatar',
    'hardware Qatar',
    'electrical items Qatar',
    'plumbing items Doha',
    'construction materials Qatar',
    'LED tubes Qatar',
    'fluorescent tubes Doha',
    'lighting solutions Qatar',
    'switches plugs Qatar',
    'breakers Qatar',
    'wiring accessories Doha',
    'conduit pipes Qatar',
    'cable trays Doha',
    'electrical tools Qatar',
    'plumbing pipes Doha',
    'fittings Qatar',
    'valves Doha',
    'sanitary fittings Qatar',
    'tiles Qatar',
    'cement Doha',
    'steel Qatar',
    'wood Doha',
    'paint Qatar',
    'adhesives Doha',
    'fasteners Qatar',
    'tools Doha',
    'safety equipment Qatar',
    'Al Alis trading',
    'building materials Doha',
    'electrical Doha',
    'plumbing Qatar',
  ],
  authors: [{ name: COMPANY_NAME }],
  creator: COMPANY_NAME,
  publisher: COMPANY_NAME,
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'en_QA',
    url: siteConfig.url,
    title: `${COMPANY_NAME} | Building Materials, Electrical & Plumbing Supplies in Doha, Qatar`,
    description: siteConfig.description,
    siteName: COMPANY_NAME,
    images: [
      {
        url: siteConfig.ogImage,
        width: 1200,
        height: 630,
        alt: COMPANY_NAME,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: `${COMPANY_NAME} | Building Materials, Electrical & Plumbing Supplies in Doha, Qatar`,
    description: siteConfig.description,
    images: [siteConfig.ogImage],
    creator: '@alalistrading',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'your-google-verification-code',
  },
  icons: {
    icon: [
      { url: '/favicon.png', type: 'image/png' },
    ],
    apple: [
      { url: '/favicon.png', type: 'image/png' },
    ],
    shortcut: '/favicon.png',
  },
  alternates: {
    canonical: siteConfig.url,
  },
};

export function generateOrganizationSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: COMPANY_NAME,
    url: siteConfig.url,
    logo: `${siteConfig.url}/logo.png`,
    description: siteConfig.description,
    foundingDate: '2000',
    address: {
      '@type': 'PostalAddress',
      streetAddress: ADDRESS.split(',')[0],
      addressLocality: 'Doha',
      postalCode: PO_BOX,
      addressCountry: 'QA',
    },
    contactPoint: {
      '@type': 'ContactPoint',
      telephone: PHONE_NUMBER,
      email: EMAIL,
      contactType: 'customer service',
      availableLanguage: ['English', 'Arabic'],
    },
    sameAs: [
      SOCIAL_LINKS.facebook,
      SOCIAL_LINKS.instagram,
      SOCIAL_LINKS.twitter,
      SOCIAL_LINKS.linkedin,
    ],
  };
}

export function generateLocalBusinessSchema() {
  return {
    '@context': 'https://schema.org',
    '@type': 'HardwareStore',
    name: COMPANY_NAME,
    image: `${siteConfig.url}/logo.png`,
    '@id': siteConfig.url,
    url: siteConfig.url,
    telephone: PHONE_NUMBER,
    email: EMAIL,
    address: {
      '@type': 'PostalAddress',
      streetAddress: ADDRESS.split(',')[0],
      addressLocality: 'Madinat Khalifa South',
      addressRegion: 'Ad Dawhah',
      postalCode: PO_BOX,
      addressCountry: 'QA',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 25.3024,
      longitude: 51.4898,
    },
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday'],
        opens: '06:00',
        closes: '22:00',
      },
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: 'Friday',
        opens: '18:00',
        closes: '22:00',
      },
    ],
    priceRange: '$$',
    areaServed: {
      '@type': 'Country',
      name: 'Qatar',
    },
  };
}
